### ISSUE TITLE
Running ve4 locally

### ISSUE THREAD

**Issue by 1-Kelvin** [Open-MBEE/ve-confluence#21]
Hello, 

I am trying to run ve4 with following docker image [link](https://hub.docker.com/r/openmbee/mms), but cannot find a way to actually run the view editor. 

Is there a more comprehensive guide out there?
Which version do you recommend for running the ve4 locally?

cheers

**Comment by blake-regalia** [comment]
hey @1-Kelvin . Unfortunately we don't have a more comprehensive guide at this time for setting up the environment. Perhaps I can help you over email or slack, though. Are you on the openmbee community slack group? https://openmbee.slack.com/

**Comment by avianinc** [comment]
@blake-regalia were you able to help @1-Kelvin get this up and running... I'm assuming this is the only ve version that will work with mdk5.x. If you guys have any build notes I would appreciate them.

**Comment by dlamoris** [comment]
repo name changed to reflect different deployment
