### ISSUE TITLE
Pages containing "/" in the page name show "null" in the page URL

### ISSUE THREAD

**Issue by dlamoris** [Open-MBEE/ve-confluence#48]
Steps to reproduce:

Create new confluence page

Enter in a title and include “/”

Add confluence-ve macro

Save page

Page is saved and the URL contains “https://some-confluence-server.com/display/null/null”

**Comment by jwest115** [comment]
"null" URLs also seem to appear for any page name that contains special characters (tested with # and saw the same behavior)
